import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../../public/styles/globals.css";
import { ReactNode } from "react";
import NextNProgress from "nextjs-progressbar";
import { ThemeProvider } from "next-themes";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ThemeProvider>
          <NextNProgress
            color="red"
            height={4}
            options={{ showSpinner: false }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
